#!/usr/bin/env bash
#
# Build a throwaway, hermetic workspace for an asciinema demo.
#
#   imperative  - structural transforms (replace + move) + a tip apply_patch
#   generative  - move + a generative agent_transform (needs a logged-in claude)
#
# Both land acme/widget under //third_party/widget/lib. Prints the monorepo path.
#
# Usage: setup.sh <workdir> <imperative|generative>
set -euo pipefail
WORK="${1:?usage: setup.sh <workdir> <imperative|generative>}"
MODE="${2:?usage: setup.sh <workdir> <imperative|generative>}"
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
FIXTURE="$REPO_ROOT/examples/transforms/widget-origin"

gc(){ git -c user.email=demo@capyfun.dev -c user.name=CapyFun -c commit.gpgsign=false -C "$1" "${@:2}"; }

rm -rf "$WORK"; mkdir -p "$WORK"

# --- upstream (stands in for github.com/acme/widget) ------------------------
ORIGIN="$WORK/origins/acme/widget"
mkdir -p "$ORIGIN"
cp -r "$FIXTURE/." "$ORIGIN/"
gc "$ORIGIN" init -q -b main
gc "$ORIGIN" add -A
gc "$ORIGIN" commit -qm "initial widget"
sed -i 's#acme.internal/log v1.4.0#acme.internal/log v1.5.0#' "$ORIGIN/go.mod"
gc "$ORIGIN" commit -qam "bump acme.internal/log to v1.5.0"

# --- monorepo ---------------------------------------------------------------
MONO="$WORK/mono"
mkdir -p "$MONO/third_party/widget"
gc "$MONO" init -q -b main
cat > "$MONO/SRC" <<'EOF'
monorepo(name = "tinytree", default_branch = "main")
EOF

if [ "$MODE" = imperative ]; then
    # toolchain patch (the tip apply_patch transform)
    SCRATCH="$WORK/scratch"; mkdir -p "$SCRATCH" "$MONO/third_party/widget/patches"
    gc "$SCRATCH" init -q
    cp "$ORIGIN/go.mod" "$SCRATCH/go.mod"
    gc "$SCRATCH" add -A; gc "$SCRATCH" commit -qm base
    awk '{ print } /^go 1\.21$/ { print ""; print "toolchain go1.21.6" }' \
        "$ORIGIN/go.mod" > "$SCRATCH/go.mod.new"
    mv "$SCRATCH/go.mod.new" "$SCRATCH/go.mod"
    gc "$SCRATCH" diff > "$MONO/third_party/widget/patches/0001-pin-toolchain.patch"

    cat > "$MONO/third_party/widget/SRC" <<'EOF'
# Imperative transforms: deterministic, rewrite every mirrored commit.
github_import(
    name = "widget",
    repo = "acme/widget",
    transforms = [
        replace(before = "acme.internal/", after = "", paths = ["**/*.go"]),
        move(src = "pkg", dst = "lib"),
        apply_patch("patches/0001-pin-toolchain.patch"),
    ],
)
EOF

elif [ "$MODE" = generative ]; then
    # agent tooling (composable, referenced by label)
    mkdir -p "$MONO/tools/harness" "$MONO/tools/models" "$MONO/tools/agent/prompts"
    cat > "$MONO/tools/harness/SRC" <<'EOF'
harness(name = "claude_code", kind = "claude_code")
EOF
    cat > "$MONO/tools/models/SRC" <<'EOF'
model(name = "sonnet", provider = "anthropic", id = "claude-sonnet-4-6")
EOF
    cat > "$MONO/tools/agent/SRC" <<'EOF'
agent(name = "modernizer",
      harness = "//tools/harness:claude_code",
      model   = "//tools/models:sonnet")
EOF
    cat > "$MONO/tools/agent/prompts/SRC" <<'EOF'
prompt_template(name = "modernize", src = "modernize.tmpl")
EOF
    cat > "$MONO/tools/agent/prompts/modernize.tmpl" <<'EOF'
Add this exact line as the very first line of every .go file under lib/:
// Code generated by CapyFun import; modernized for the monorepo.
Make no other changes. Do not create any new files.
EOF

    cat > "$MONO/third_party/widget/SRC" <<'EOF'
# Generative transform: a coding agent modernizes the landed code.
github_import(
    name = "widget",
    repo = "acme/widget",
    transforms = [
        move(src = "pkg", dst = "lib"),
        agent_transform(
            agent  = "//tools/agent:modernizer",
            prompt = template("//tools/agent/prompts:modernize"),
            paths  = ["lib/**"],
        ),
    ],
)
EOF
else
    echo "unknown mode: $MODE (want imperative|generative)" >&2; exit 2
fi

gc "$MONO" add -A
gc "$MONO" commit -qm "configure widget import ($MODE)"

echo "$MONO"
