use super::*;
use crate::vendorgen::Vendored;

const MANIFEST: &str = r#"
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = { version = "1", features = ["std"] }   # inline table
patched = { git = "https://github.com/acme/patched", rev = "abc123" }
serde = { workspace = true }

[dev-dependencies]
tempfile = "3"
"#;

const LOCK: &str = r#"
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "anyhow"
version = "1.0.86"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b3d1d046238990b9cf5bcde22a3fb3584ee5cf65fb2765f454ed428c7a0063da"

[[package]]
name = "patched"
version = "0.2.0"
source = "git+https://github.com/acme/patched?rev=abc123#abc123def456"

[[package]]
name = "tempfile"
version = "3.27.0"
"#;

#[test]
fn parses_manifest_dependencies_only() {
    let deps = parse_manifest(MANIFEST);
    let names: Vec<&str> = deps.iter().map(|d| d.name.as_str()).collect();
    // [dev-dependencies] is excluded.
    assert_eq!(names, vec!["anyhow", "thiserror", "patched", "serde"]);

    let anyhow = &deps[0];
    assert_eq!(anyhow.req, "1");
    assert!(anyhow.git.is_none());

    let thiserror = &deps[1];
    assert_eq!(thiserror.req, "1", "version pulled from inline table");

    let patched = &deps[2];
    assert_eq!(
        patched.git.as_deref(),
        Some("https://github.com/acme/patched")
    );
    assert_eq!(patched.req, "", "git dep has no version requirement");
}

#[test]
fn parses_lock_packages() {
    let lock = parse_lock(LOCK);
    assert_eq!(lock["anyhow"].version, "1.0.86");
    assert!(lock["anyhow"]
        .source
        .as_deref()
        .unwrap()
        .starts_with("registry+"));
    assert!(lock["patched"]
        .source
        .as_deref()
        .unwrap()
        .starts_with("git+"));
}

#[test]
fn plan_resolves_exact_version_and_git_sha() {
    let deps = parse_manifest(MANIFEST);
    let lock = parse_lock(LOCK);
    let planned = plan(&deps, &lock, "third_party/rust");

    // Sorted by package_dir.
    let dirs: Vec<&str> = planned.iter().map(|p| p.package_dir.as_str()).collect();
    assert_eq!(
        dirs,
        vec![
            "third_party/rust/anyhow",
            "third_party/rust/patched",
            "third_party/rust/serde",
            "third_party/rust/thiserror",
        ]
    );

    let anyhow = planned.iter().find(|p| p.name == "anyhow").unwrap();
    assert_eq!(anyhow.version, "1.0.86", "exact version from the lock");
    assert!(
        anyhow.git_url.is_none(),
        "registry crate resolves over network"
    );

    let patched = planned.iter().find(|p| p.name == "patched").unwrap();
    assert_eq!(
        patched.git_url.as_deref(),
        Some("https://github.com/acme/patched")
    );
    assert_eq!(
        patched.git_sha.as_deref(),
        Some("abc123def456"),
        "exact SHA from the git-source lock entry — no network needed"
    );
    assert_eq!(
        slug_from_git(patched),
        Some(("acme".into(), "patched".into()))
    );
}

#[test]
fn plan_falls_back_to_requirement_without_lock() {
    let deps = parse_manifest(MANIFEST);
    let planned = plan(&deps, &BTreeMap::new(), "third_party/rust");
    let anyhow = planned.iter().find(|p| p.name == "anyhow").unwrap();
    assert_eq!(anyhow.version, "1", "manifest requirement when no lock");
}

#[test]
fn render_src_shape() {
    let v = Vendored {
        name: "anyhow".into(),
        slug: "dtolnay/anyhow".into(),
        version: "1.0.86".into(),
        commit: "841522b2aa09732fecee40804440d2c35c68c480".into(),
        tag: "1.0.86".into(),
    };
    let src = render_src(&v);
    assert!(src.contains("git_repository("));
    assert!(src.contains("name = \"anyhow\""));
    assert!(src.contains("repo = \"dtolnay/anyhow\""));
    assert!(src.contains("commit = \"841522b2aa09732fecee40804440d2c35c68c480\""));
}
