//! `package.json` / `package-lock.json` reader for scaffolding `git_repository`
//! snapshot rules (coarse-grained: one `SRC` at the language root with a target
//! per package, each landing in its own `into` subdirectory).
//!
//! Registry packages carry no upstream repo, so their GitHub slug + commit are
//! resolved over the network in the CLI layer. This reader is pure (no npm
//! toolchain or network) and uses `serde_json` since both files are JSON.

use std::collections::BTreeMap;

use anyhow::{Context, Result};
use serde_json::Value;

use crate::vendorgen::Vendored;

/// A `dependencies` entry from a `package.json`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Dep {
    pub name: String,
    /// Semver range string (e.g. `^6.2.1`).
    pub range: String,
}

/// A planned package snapshot before network resolution.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Planned {
    pub name: String,
    /// Exact version (from the lock) or the range stripped of its operator.
    pub version: String,
    /// Subdirectory under the language root this package lands in (`into`).
    pub into: String,
}

/// Parse `dependencies` of a `package.json`.
pub fn parse_manifest(content: &str) -> Result<Vec<Dep>> {
    let v: Value = serde_json::from_str(content).context("parsing package.json")?;
    let mut out = Vec::new();
    if let Some(obj) = v.get("dependencies").and_then(Value::as_object) {
        for (name, range) in obj {
            out.push(Dep {
                name: name.clone(),
                range: range.as_str().unwrap_or_default().to_owned(),
            });
        }
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

/// Parse a `package-lock.json` into `name -> exact version`. Supports the v2/v3
/// `packages` map (top-level `node_modules/<name>` entries only) and the legacy
/// v1 `dependencies` map.
pub fn parse_lock(content: &str) -> Result<BTreeMap<String, String>> {
    let v: Value = serde_json::from_str(content).context("parsing package-lock.json")?;
    let mut out = BTreeMap::new();
    if let Some(pkgs) = v.get("packages").and_then(Value::as_object) {
        for (path, meta) in pkgs {
            // Top-level installs only: exactly one `node_modules/` segment, so a
            // nested `.../node_modules/...` (a transitive dup) is skipped.
            let Some(name) = path.strip_prefix("node_modules/") else {
                continue;
            };
            if name.contains("/node_modules/") {
                continue;
            }
            if let Some(ver) = meta.get("version").and_then(Value::as_str) {
                out.insert(name.to_owned(), ver.to_owned());
            }
        }
    }
    if let Some(deps) = v.get("dependencies").and_then(Value::as_object) {
        for (name, meta) in deps {
            if let Some(ver) = meta.get("version").and_then(Value::as_str) {
                out.entry(name.clone()).or_insert_with(|| ver.to_owned());
            }
        }
    }
    Ok(out)
}

/// Plan package snapshots: resolve each manifest dep's exact version from the
/// lock (falling back to the range with its operator stripped) and assign an
/// `into` subdirectory. Deduplicated by name, sorted for deterministic output.
pub fn plan(deps: &[Dep], lock: &BTreeMap<String, String>) -> Vec<Planned> {
    let mut planned: Vec<Planned> = Vec::new();
    for dep in deps {
        let version = lock
            .get(&dep.name)
            .cloned()
            .unwrap_or_else(|| strip_range(&dep.range));
        let p = Planned {
            name: dep.name.clone(),
            version,
            into: dep.name.clone(),
        };
        if !planned.iter().any(|e| e.name == p.name) {
            planned.push(p);
        }
    }
    planned.sort_by(|a, b| a.name.cmp(&b.name));
    planned
}

/// Render the single coarse-grained `SRC` body for all resolved packages.
pub fn render_src(vendored: &[(Vendored, String)]) -> String {
    let mut s = String::from(
        "# Generated by `capyfun gen-npm` from package.json.\n\
         # Coarse-grained: one SRC for the language dir, a target per package.\n\
         # Each target uses `into` so destinations do not overlap.\n",
    );
    for (v, into) in vendored {
        s.push_str(&format!(
            "\ngit_repository(\n    name = {:?},\n    repo = {:?},\n    commit = {:?},\n    into = {:?},\n)\n",
            v.name, v.slug, v.commit, into
        ));
    }
    s
}

/// Strip a leading semver operator (`^`, `~`, `>=`, `=`, `v`) from a range so it
/// can seed tag candidates when no lockfile pins an exact version.
fn strip_range(range: &str) -> String {
    range
        .trim()
        .trim_start_matches(['^', '~', '>', '=', '<', ' ', 'v'])
        .to_owned()
}

#[cfg(test)]
mod tests;
